# LAB 04

## Multi-variable linear regression

In [10]:
import tensorflow as tf
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180. , 196., 142.]

# placeholders for a tensorflow that will be always fed.
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name = 'weight1')
w2 = tf.Variable(tf.random_normal([1]), name = 'weight2')
w3 = tf.Variable(tf.random_normal([1]), name = 'weight3')
b = tf.Variable(tf.random_normal([1]), name = 'bias')
hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))
# Minimize. Need a very small learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session
sess = tf.Session()
# Initializes global variables in the graph
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict = {x1:x1_data, x2 : x2_data, x3 : x3_data, Y : y_data})
    if step % 200 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)
                                                                           

0 Cost:  28828.52 
Prediction:
 [2.692666  2.2698078 2.6505089 2.6617503 1.9033068]
200 Cost:  1.9092582 
Prediction:
 [153.2382  183.40993 181.0294  196.921   140.10873]
400 Cost:  1.7331184 
Prediction:
 [153.1402  183.47733 180.99966 196.89711 140.1992 ]
600 Cost:  1.5750437 
Prediction:
 [153.04744 183.54117 180.97153 196.87445 140.28496]
800 Cost:  1.4331238 
Prediction:
 [152.9596  183.60161 180.9449  196.85284 140.36626]
1000 Cost:  1.3057489 
Prediction:
 [152.87645 183.65886 180.91972 196.83232 140.44331]
1200 Cost:  1.1914042 
Prediction:
 [152.79774 183.71303 180.8959  196.81276 140.51639]
1400 Cost:  1.0887371 
Prediction:
 [152.72322 183.76434 180.87337 196.79417 140.58568]
1600 Cost:  0.99658364 
Prediction:
 [152.65273 183.81294 180.85207 196.77649 140.65137]
1800 Cost:  0.9138342 
Prediction:
 [152.58595 183.85892 180.83188 196.75961 140.71364]
2000 Cost:  0.8395311 
Prediction:
 [152.52277 183.90247 180.81282 196.74355 140.7727 ]


## Multi-variable linear regression using Matrics

In [16]:
import tensorflow as tf
x_data = [[73.,80.,75.], [93.,88.,93.], [89.,91.,90.],[96.,98.,100.],[73.,66.,70.]]
y_data = [[152.],[185.],[180.],[196.],[142.]]
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3,1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))
# Minimize. Need a very small learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session
sess = tf.Session()
# Initializes global variables in the graph
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict = {X : x_data, Y : y_data})
    if step % 200 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)
                                                                           

0 Cost:  121287.21 
Prediction:
 [[-156.70761]
 [-187.78513]
 [-185.7894 ]
 [-197.7756 ]
 [-146.62752]]
200 Cost:  10.098417 
Prediction:
 [[152.14836]
 [183.7125 ]
 [180.11205]
 [200.67317]
 [136.80757]]
400 Cost:  9.64963 
Prediction:
 [[152.01167]
 [183.80858]
 [180.07321]
 [200.62143]
 [136.95366]]
600 Cost:  9.2414 
Prediction:
 [[151.8827 ]
 [183.89934]
 [180.03671]
 [200.57146]
 [137.09264]]
800 Cost:  8.869596 
Prediction:
 [[151.76106]
 [183.98509]
 [180.00246]
 [200.52324]
 [137.22495]]
1000 Cost:  8.530556 
Prediction:
 [[151.64636]
 [184.06609]
 [179.9703 ]
 [200.47667]
 [137.3509 ]]
1200 Cost:  8.220975 
Prediction:
 [[151.53822]
 [184.14256]
 [179.94019]
 [200.43167]
 [137.47086]]
1400 Cost:  7.9377913 
Prediction:
 [[151.4363 ]
 [184.21477]
 [179.91191]
 [200.38812]
 [137.58511]]
1600 Cost:  7.678496 
Prediction:
 [[151.34027]
 [184.28294]
 [179.88547]
 [200.34604]
 [137.69397]]
1800 Cost:  7.4405565 
Prediction:
 [[151.2498 ]
 [184.34727]
 [179.86069]
 [200.30524]
 [137

## Loading data from file

#### tf.set_random_seed(777) : for reproductibility
#### import numpy as np
#### np.loadtxt('data-01-test-score.csv', delimiter = ',', dtype = np.float32)

In [16]:
import tensorflow as tf
import numpy as np
tf.set_random_seed(777)

xy = np.loadtxt('data-01-test-score.csv',delimiter=',', dtype=np.float32)
x_data = xy[:,0:-1]
y_data = xy[:,[-1]]

# Make sure the shape and data are OK
print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data, len(y_data))

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3,1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

# Hypothesis
hypothesis = tf.matmul(X,W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

(6, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]] 6
(6, 1) [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]] 6


In [3]:
# Launch the graph in a session
sess = tf.Session()

# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

# Set up feed_dict variables inside the loop.
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict = {X:x_data, Y:y_data})
    if step % 500 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)
        
# Ask my score
print("Your score will be ", sess.run(hypothesis, feed_dict={X:[[100,70,101]]}))
print("Other score will be ", sess.run(hypothesis, feed_dict={X:[[60,70,110], [90,100,80]]}))

0 Cost:  20344.273 
Prediction:
 [[22.048063 ]
 [21.619787 ]
 [24.096693 ]
 [22.293005 ]
 [18.633902 ]
 [ 7.2669735]]
500 Cost:  5.194362 
Prediction:
 [[155.39178]
 [182.79918]
 [182.4304 ]
 [194.83575]
 [141.69955]
 [ 98.26765]]
1000 Cost:  4.1113534 
Prediction:
 [[154.95578]
 [183.00641]
 [182.2495 ]
 [194.73842]
 [141.95724]
 [ 98.69708]]
1500 Cost:  3.3275473 
Prediction:
 [[154.58617]
 [183.18124]
 [182.09547]
 [194.65872]
 [142.1719 ]
 [ 99.06362]]
2000 Cost:  2.7586195 
Prediction:
 [[154.27278 ]
 [183.32866 ]
 [181.96426 ]
 [194.5939  ]
 [142.35019 ]
 [ 99.376816]]
Your score will be  [[171.15341]]
Other score will be  [[106.725494]
 [197.8313  ]]


## Loading data from file using batches

#### (X) tf.train.string_input_producer() : Filename Queue
#### (X) tf.TextLineReader(), reader.read() : text file 읽기
#### tf.decode_csv() : csv file decode
#### tf.train.batch() : collect batches of csv in<br>

#### [ Start populating the filename queue. ]
#### coord = tf.train.Coordinator()
#### threads = tf.train.start_queue_runners(sess=sess, coord=coord)
#### coord.request_stop()
#### coord.join(threads)

In [2]:
import tensorflow as tf
filename_queue = tf.train.string_input_producer(['data-01-test-score.csv'], shuffle = False, name = 'filename_queue')

reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

# Default values, in case of empty columns. Also specifies the type of the decoded result.
record_defaults = [[0.], [0.], [0.], [0.]]
xy = tf.decode_csv(value, record_defaults = record_defaults)

# collect batches of csv in
train_x_batch, train_y_batch = tf.train.batch([xy[0:-1], xy[-1:]], batch_size = 10)

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3,1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

# Hypothesis
hypothesis = tf.matmul(X,W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

In [18]:
# Launch the graph in a sessoion
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

# Start populating the filename queue
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict = {X: x_batch, Y: y_batch})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction\n", hy_val)
        
coord.request_stop()
coord.join(threads)

INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InvalidArgumentError'>, Field 0 in record 0 is not a valid float: #EXAM1
	 [[{{node DecodeCSV}}]]


OutOfRangeError: FIFOQueue '_53_batch_4/fifo_queue' is closed and has insufficient elements (requested 10, current size 0)
	 [[node batch_4 (defined at <ipython-input-17-a97728853737>:12) ]]

Original stack trace for 'batch_4':
  File "C:\Users\SAMSUNG\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\SAMSUNG\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\SAMSUNG\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\Users\SAMSUNG\Anaconda3\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\Users\SAMSUNG\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 505, in start
    self.io_loop.start()
  File "C:\Users\SAMSUNG\Anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 148, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\SAMSUNG\Anaconda3\lib\asyncio\base_events.py", line 539, in run_forever
    self._run_once()
  File "C:\Users\SAMSUNG\Anaconda3\lib\asyncio\base_events.py", line 1775, in _run_once
    handle._run()
  File "C:\Users\SAMSUNG\Anaconda3\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\SAMSUNG\Anaconda3\lib\site-packages\tornado\ioloop.py", line 690, in <lambda>
    lambda f: self._run_callback(functools.partial(callback, future))
  File "C:\Users\SAMSUNG\Anaconda3\lib\site-packages\tornado\ioloop.py", line 743, in _run_callback
    ret = callback()
  File "C:\Users\SAMSUNG\Anaconda3\lib\site-packages\tornado\gen.py", line 787, in inner
    self.run()
  File "C:\Users\SAMSUNG\Anaconda3\lib\site-packages\tornado\gen.py", line 748, in run
    yielded = self.gen.send(value)
  File "C:\Users\SAMSUNG\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 365, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "C:\Users\SAMSUNG\Anaconda3\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Users\SAMSUNG\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 272, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "C:\Users\SAMSUNG\Anaconda3\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Users\SAMSUNG\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 542, in execute_request
    user_expressions, allow_stdin,
  File "C:\Users\SAMSUNG\Anaconda3\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Users\SAMSUNG\Anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 294, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\Users\SAMSUNG\Anaconda3\lib\site-packages\ipykernel\zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "C:\Users\SAMSUNG\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2854, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "C:\Users\SAMSUNG\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2880, in _run_cell
    return runner(coro)
  File "C:\Users\SAMSUNG\Anaconda3\lib\site-packages\IPython\core\async_helpers.py", line 68, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\SAMSUNG\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3057, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\Users\SAMSUNG\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3248, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "C:\Users\SAMSUNG\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3325, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-17-a97728853737>", line 12, in <module>
    train_x_batch, train_y_batch = tf.train.batch([xy[0:-1], xy[-1:]], batch_size = 10)
  File "C:\Users\SAMSUNG\Anaconda3\lib\site-packages\tensorflow\python\util\deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "C:\Users\SAMSUNG\Anaconda3\lib\site-packages\tensorflow\python\training\input.py", line 1021, in batch
    name=name)
  File "C:\Users\SAMSUNG\Anaconda3\lib\site-packages\tensorflow\python\training\input.py", line 790, in _batch
    dequeued = queue.dequeue_many(batch_size, name=name)
  File "C:\Users\SAMSUNG\Anaconda3\lib\site-packages\tensorflow\python\ops\data_flow_ops.py", line 488, in dequeue_many
    self._queue_ref, n=n, component_types=self._dtypes, name=name)
  File "C:\Users\SAMSUNG\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_data_flow_ops.py", line 3861, in queue_dequeue_many_v2
    timeout_ms=timeout_ms, name=name)
  File "C:\Users\SAMSUNG\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\SAMSUNG\Anaconda3\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\Users\SAMSUNG\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3616, in create_op
    op_def=op_def)
  File "C:\Users\SAMSUNG\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()


tf.TextLineReader, tf.train.string_input_producer 삭제 <br>
tf.data.Dataset 통해서 구현

#### tf.data.TextLineDataset() : 데이터 읽어오기
#### iterator.get_next() : 반복자가 다음 데이터를 읽어오도록 dataset 노드에 명령을 저장

In [20]:
import tensorflow as tf

#tf.data를 이용하여 파일에서 데이터 읽어오기
#.skip(1) : 첫번째 줄은 제외하고(헤더)
#.repeat() : 파일의 끝에 도달하더라도 처음부터 무한 반복
#.batch(10) : 한 번에 10개씩 묶어서 사용
iterator = tf.data.TextLineDataset("data-01-test-score.csv")\
           .skip(1)\
           .repeat()\
           .batch(10)\
           .make_initializable_iterator();

# 반복자가 다음 데이터를 읽어오도록 dataset 노드에 명령을 저장
dataset = iterator.get_next()

#csv를 읽어서 데이터로 변환한다.
lines = tf.decode_csv(dataset, record_defaults=[[0.], [0.], [0.], [0.]])
#변환된 데이터의 첫번째 열부터 마지막-1번째 열까지 합쳐서 train_x_batch에 할당
train_x_batch = tf.stack(lines[0:-1], axis=1)
#마지막 열을 합쳐서 train_y_batch에 할당
train_y_batch = tf.stack(lines[-1:], axis=1)

#placeholder는 실제 값이 입력된다.
X = tf.placeholder(tf.float32, shape=[None, 3]) #x값은 Nx3의 행렬이다.
y = tf.placeholder(tf.float32, shape=[None, 1]) #y값은 Nx1의 행렬이다.

#Variable은 모델을 훈련하여 업데이트 된다.
W = tf.Variable(tf.random_normal([3,1]), name="weight") #3x1의 행렬(3행 1열)
b = tf.Variable(tf.random_normal([1]), name="bias")

#가설h
h = tf.matmul(X, W) + b

#loss(cost) 함수
loss = tf.reduce_mean(tf.square(h - y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(loss)

ss = tf.Session()
ss.run(tf.global_variables_initializer())

for step in range(2001):
    #반복자 초기화
    ss.run(iterator.initializer)
    #반복자를 통해 할당된 값을 읽어오기
    x_batch, y_batch = ss.run([train_x_batch, train_y_batch])
    #모델 훈련을 진행하고 loss및 h값 가져오기
    loss_val, h_val, _ = ss.run([loss, h, train],
                                     feed_dict={X: x_batch, y: y_batch})
    if step % 500 == 0:
        print("loss : {0}".format(loss_val))

print("score..", ss.run(h, feed_dict={X:[[100,70,101]]}))

loss : 36436.23828125
loss : 2.7317516803741455
loss : 2.2529168128967285
loss : 1.896484136581421
loss : 1.6311336755752563
score.. [[187.21309]]
