# LAB08

## Tensor Manipulation

#### Shape, Rank, Axis

In [51]:
import tensorflow as tf
import numpy as np

In [15]:
sess = tf.Session()

with sess.as_default():
    t = tf.constant([1,2,3,4])
    print("Shape :", tf.shape(t).eval(), "Rank :", tf.rank(t).eval())

Shape : [4] Rank : 1


In [16]:
with sess.as_default():
    t = tf.constant([[1,2], [3,4]])
    print("Shape :", tf.shape(t).eval(), "Rank :", tf.rank(t).eval())

Shape : [2 2] Rank : 2


In [17]:
with sess.as_default():
    t = tf.constant([[[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[13,14,15,16],[17,18,19,20],[21,22,23,24]]]])
    print("Shape :", tf.shape(t).eval(), "Rank :", tf.rank(t).eval())

Shape : [1 2 3 4] Rank : 4


#### Matmul VS multiply

In [22]:
# Matmul
matrix1 = tf.constant([[1.,2.],[3.,4.]])
matrix2 = tf.constant([[1.],[2.]])

print("Matrix 1 shape", matrix1.shape)
print("Matrix 2 shape", matrix2.shape)

with sess.as_default():
    print(tf.matmul(matrix1, matrix2).eval())

Matrix 1 shape (2, 2)
Matrix 2 shape (2, 1)
[[ 5.]
 [11.]]


In [23]:
# multiply
with sess.as_default():
    print((matrix1*matrix2).eval())

[[1. 2.]
 [6. 8.]]


In [25]:
# Broadcasting
matrix1 = tf.constant([3.,3.])
matrix2 = tf.constant([2.,2.])
with sess.as_default():
    print((matrix1 + matrix2).eval()) 

[5. 5.]


In [26]:
# Broadcasting
matrix1 = tf.constant([[1.,2.]])
matrix2 = tf.constant(3.)
with sess.as_default():
    print((matrix1 + matrix2).eval()) 

[[4. 5.]]


In [28]:
# Broadcasting
matrix1 = tf.constant([[1.,2.]])
matrix2 = tf.constant([3., 4.])
with sess.as_default():
    print((matrix1 + matrix2).eval()) 

[[4. 6.]]


In [29]:
# Broadcasting
matrix1 = tf.constant([[1.,2.]])
matrix2 = tf.constant([[3.], [4.]])
with sess.as_default():
    print((matrix1 + matrix2).eval()) 

[[4. 5.]
 [5. 6.]]


#### Reduce mean

In [33]:
with sess.as_default():
    print(tf.reduce_mean([1,2], axis = 0).eval())

1


In [36]:
x = [[1., 2.],
     [3., 4.]]
with sess.as_default():
    print(tf.reduce_mean(x).eval())

2.5


In [37]:
with sess.as_default():
    print(tf.reduce_mean(x, axis = 0).eval())

[2. 3.]


In [38]:
with sess.as_default():
    print(tf.reduce_mean(x, axis = 1).eval())

[1.5 3.5]


#### Reduce sum

In [39]:
with sess.as_default():
    print(tf.reduce_sum(x).eval())

10.0


In [40]:
with sess.as_default():
    print(tf.reduce_sum(x, axis = 0).eval())

[4. 6.]


In [41]:
with sess.as_default():
    print(tf.reduce_sum(x, axis = 1).eval())

[3. 7.]


In [43]:
with sess.as_default():
    print(tf.reduce_mean(tf.reduce_sum(x, axis = -1)).eval())

5.0


#### Argmax

In [48]:
x = [[0,1,2],
     [2,1,0]]
with sess.as_default():
    print(tf.argmax(x, axis = 0).eval())

[1 0 0]


In [49]:
x = [[0,1,2],
     [2,1,0]]
with sess.as_default():
    print(tf.argmax(x, axis = -1).eval())

[2 0]


#### Reshape **

In [52]:
t= np.array([[[0,1,2],
             [3,4,5]],
             [[6,7,8],
              [9,10,11]]])
t.shape

(2, 2, 3)

In [53]:
with sess.as_default():
    print(tf.reshape(t, shape = [-1,3]).eval())

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [54]:
with sess.as_default():
    print(tf.reshape(t, shape = [-1,1,3]).eval())

[[[ 0  1  2]]

 [[ 3  4  5]]

 [[ 6  7  8]]

 [[ 9 10 11]]]


In [56]:
# squeeze, expand
with sess.as_default():
    print(tf.squeeze([[0],[1],[2]]).eval())

[0 1 2]


In [60]:
with sess.as_default():
    print(tf.expand_dims([0,1,2],1).eval())

[[0]
 [1]
 [2]]


#### One hot

In [62]:
with sess.as_default():
    print(tf.one_hot([[0],[1],[2],[0]], depth = 3).eval())

[[[1. 0. 0.]]

 [[0. 1. 0.]]

 [[0. 0. 1.]]

 [[1. 0. 0.]]]


In [63]:
with sess.as_default():
    t = tf.one_hot([[0],[1],[2],[0]], depth = 3)
    print(tf.reshape(t, shape = [-1,3]).eval())

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


#### Casting

In [64]:
with sess.as_default():
    print(tf.cast([1.0,2.2,3.3,4.9], tf.int32).eval())
    print(tf.cast([True, False, 1==1, 0==1], tf.int32).eval())

[1 2 3 4]
[1 0 1 0]


####  Stack

In [65]:
x = [1,4]
y = [2,5]
z = [3,6]

# Pack along first dim.
with sess.as_default():
    print(tf.stack([x,y,z]).eval())

[[1 4]
 [2 5]
 [3 6]]


In [68]:
with sess.as_default():
    print(tf.stack([x,y,z], axis = 1).eval())

[[1 2 3]
 [4 5 6]]


#### Ones and Zeros like

In [69]:
x = [[0,1,2],
    [2,1,0]]

with sess.as_default():
    print(tf.ones_like(x).eval())

[[1 1 1]
 [1 1 1]]


In [70]:
with sess.as_default():
    print(tf.zeros_like(x).eval())

[[0 0 0]
 [0 0 0]]


#### Zip

In [71]:
for x, y in zip([1,2,3],[4,5,6]):
    print(x,y)

1 4
2 5
3 6


In [72]:
for x, y, z in zip([1,2,3],[4,5,6],[7,8,9]):
    print(x,y,z)

1 4 7
2 5 8
3 6 9
